### ISSUE TITLE
Init scene button throws exception

### ISSUE THREAD

**Issue by NothingHereIsReal** [hapit/blender_addon_dynamic_slideshow#27]
Clicking the Init scene button in Blender 2.79b throws the following exception:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\dynamic_slideshow.py", line 271, in execute
    bpy.context.scene.render.use_sequencer_gl_preview = True
AttributeError: 'RenderSettings' object has no attribute 'use_sequencer_gl_preview'

location: <unknown location>:-1
```
Commenting out that line seems to allow it to proceed but you need to start with an empty scene for it to work properly.

**Comment by hapit** [comment]
@Rubicsys 
I removed the line because the attribute no longer exist in 2.79
It worked for me, except "add images as planes" changed it's default orientation.

Please explain the last sentence? What didn't work properly with an non empty scene?
For my test i used the default scene. Perhaps you could give me the non empty blend file for testing.

**Comment by NothingHereIsReal** [comment]
With the default (File | New) scene, I see this after clicking Init scene (and adding a few images).

![image](https://user-images.githubusercontent.com/1449700/38920196-976c896a-42ea-11e8-92ea-7f29a30bd878.png)

and this after clicking Setup slideshow.

![image](https://user-images.githubusercontent.com/1449700/38920233-aebb12c6-42ea-11e8-8c32-ed9c5c57f64f.png)

If I delete everything in the scene before using the addon I see this instead:

![image](https://user-images.githubusercontent.com/1449700/38920375-05292396-42eb-11e8-9952-8249988a65a8.png)

and after clicking Add camera and Setup slideshow

![image](https://user-images.githubusercontent.com/1449700/38920414-222efdb2-42eb-11e8-807b-f666fd36cd39.png)

**Comment by hapit** [comment]
Thank you. I think it's not an code issue. I need to update the documentation. 
I'll look into it.

**Comment by hapit** [comment]
@Rubicsys 
I've tested it. 
The camera position has to be initialized as well, before importing the images as planes.
Is there a need for the addon to work with an existing scene? I would like to clean the scene with the init button. I mean removing everything than and inserting my default camera. 
To make it work with existing objects would be more work. I think it would not be worth the time. Correct me if I'm wrong.

**Comment by NothingHereIsReal** [comment]
For me, there is no need to retain anything before clicking init.  It would be fine to clean the scene and start fresh.  I can't imagine a scenario where this would not apply.  Thanks.

**Comment by 3pointedit** [comment]
Sorry for the noise, just wanted to thank you for fixing this as I've just returned to use this addon in 2.79b. Tried doing this all the manual way with VSE Transforms addon and it took a half an hour!

**Comment by 3pointedit** [comment]
I also get an exception when running Init on an empty scene.
Also of note, Blender no longer allows you to Add the 3D scene that the VSE is in. Although I was able to create another scene and add the first to it, then copy that back to the original.
`Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/2.79/scripts/addons/dynamic_slideshow.py", line 196, in compair_against_online_version
    latestversion = urllib.request.urlopen('https://raw.githubusercontent.com/hapit/blender_addon_dynamic_slideshow/master/version.txt')
  File "/Applications/blender-2.79.0-git20180525.5e2f9c5c67f-x86_64/blender.app/Contents/Resources/2.79/python/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/blender-2.79.0-git20180525.5e2f9c5c67f-x86_64/blender.app/Contents/Resources/2.79/python/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Applications/blender-2.79.0-git20180525.5e2f9c5c67f-x86_64/blender.app/Contents/Resources/2.79/python/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/Applications/blender-2.79.0-git20180525.5e2f9c5c67f-x86_64/blender.app/Contents/Resources/2.79/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Applications/blender-2.79.0-git20180525.5e2f9c5c67f-x86_64/blender.app/Contents/Resources/2.79/python/lib/python3.6/urllib/request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/2.79/scripts/addons/dynamic_slideshow.py", line 261, in execute
    check_version(self)
  File "/Users/User/Library/Application Support/Blender/2.79/scripts/addons/dynamic_slideshow.py", line 211, in check_version
    if compair_against_online_version() < 0:
  File "/Users/User/Library/Application Support/Blender/2.79/scripts/addons/dynamic_slideshow.py", line 207, in compair_against_online_version
    print('except' + str(e))
UnboundLocalError: local variable 'str' referenced before assignment

location: <unknown location>:-1

`
